version: 2.1
orbs:
  codecov: codecov/codecov@3.2.0
jobs:
  build:
    working_directory: ~/presence-api
    docker:
      - image: circleci/node:12-browsers
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: ylee
          POSTGRES_DB: test_core_db
          POSTGRES_PASSWORD: password
        entrypoint: bash
        command: >
          -c '
            openssl req -nodes -new -x509 -subj "/CN=localhost" -keyout server.key -out server.crt &&
            chown postgres server.key &&
            chmod 600 /server.key &&
            exec /docker-entrypoint.sh -c ssl=on -c ssl_cert_file=/server.crt -c ssl_key_file=/server.key
          '
    steps:
      - checkout
      - restore_cache:
          key: presence-api-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: presence-api-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      # Wait for Postgres connection to open.
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: npm run test -- --coverage --no-progress
      - codecov/upload:
          file: ./coverage/lcov.info