version: 2.1
orbs:
  codecov: codecov/codecov@3.2.0
jobs:
  build:
    working_directory: ~/presence-api
    docker:
      - image: circleci/node:12-browsers
      - image: nimbustech/postgres-ssl:9.5
        environment:
          POSTGRES_USER: ylee
          POSTGRES_DB: test_core_db
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - restore_cache:
          key: presence-api-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: presence-api-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      # Wait for Postgres connection to open.
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: npm run test -- --coverage --no-progress
      - codecov/upload:
          file: ./coverage/lcov.info